name: dev_config
description: Backup your configuration files to a private repository.
version: 0.0.3
homepage: https://github.com/edufolly/dev_config

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  
  # https://pub.dev/packages/http
  http: ^1.2.0
  
  # https://pub.dev/packages/path
  path: ^1.9.0
  
  # https://pub.dev/packages/yaml
  yaml: ^3.1.2

dev_dependencies:

  # https://pub.dev/packages/lints
  flutter_lints: ^3.0.0

  # https://pub.dev/packages/test
  test: ^1.25.0
