name: dev_config
description: Backup your configuration files to a private repository.
version: 0.0.3
homepage: https://github.com/edufolly/dev_config

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  
  # https://pub.dev/packages/http
  http: ^0.13.5
  
  # https://pub.dev/packages/path
  path: ^1.8.3
  
  # https://pub.dev/packages/yaml
  yaml: ^3.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.22.2
