name: dev_config
description: Backup your configuration files to a private repository.
version: 0.0.2
homepage: https://github.com/edufolly/dev_config

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.1
  yaml: ^3.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0
