name: Dev Native Build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Linux x64 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Flutter SDK
        uses: subosito/flutter-action@v2

      - name: Build
        run: |
          dart --version
          mkdir -p build
          dart pub get
          dart compile exe -o build/dev-config bin/main.dart

      - name: Compress Build
        working-directory: build
        run: tar -cvzf dev-config-linux.tar.gz dev-config

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dev-config-linux
          path: build/dev-config-linux.tar.gz
          retention-days: 1
